name: jr_train_pos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansJP/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Black.ttf
          weight: 900
